
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jul 21 21:31:20 CEST 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 47;
  public static final int DIVIDE = 24;
  public static final int MAP = 19;
  public static final int CONST = 6;
  public static final int ASSIGNMENT = 34;
  public static final int RIGHT_SQUARE_BRACKET = 44;
  public static final int NOT_EQUAL = 27;
  public static final int SEMI = 37;
  public static final int GREATER = 28;
  public static final int CONTINUE = 14;
  public static final int INTERFACE = 20;
  public static final int LESS = 30;
  public static final int MINUS = 22;
  public static final int AND = 32;
  public static final int OR = 33;
  public static final int COMMA = 39;
  public static final int CLASS = 4;
  public static final int INC = 35;
  public static final int LESS_EQUAL = 31;
  public static final int PLUS = 21;
  public static final int MULTIPLY = 23;
  public static final int LEFT_CURLY_BRACKET = 45;
  public static final int IF = 7;
  public static final int LEFT_ROUND_BRACKET = 41;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int EQUAL = 26;
  public static final int GREATER_EQUAL = 29;
  public static final int LEFT_SQUARE_BRACKET = 43;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int NUMBER = 48;
  public static final int IDENT = 50;
  public static final int BREAK = 3;
  public static final int VOID = 12;
  public static final int COLON = 38;
  public static final int UNION = 16;
  public static final int ELSE = 5;
  public static final int POINT = 40;
  public static final int READ = 10;
  public static final int WHILE = 18;
  public static final int EXTENDS = 13;
  public static final int BOOL_CONST = 49;
  public static final int DEC = 36;
  public static final int MODUO = 25;
  public static final int RIGHT_CURLY_BRACKET = 46;
  public static final int PRINT = 9;
  public static final int DO = 17;
  public static final int RIGHT_ROUND_BRACKET = 42;
  public static final int SET = 15;
}

